package db

import (
	"context"
	"database/sql"
	"fmt"
)

// Store provides all the functions for executing db queries and transactions
type Store struct {
	// as we dont have queries for transactions we are doing composition here i.e extending like doing inheritance
	*Queries         // extending it
	db       *sql.DB // it is required to create a new db transaction
}

func NewStore(db *sql.DB) *Store {
	return &Store{
		db:      db,
		Queries: New(db), // Already generated by sqlc
	}
}

// execTx executes a function within a database transaction
func (store *Store) execTx(ctx context.Context, fn func(*Queries) error) error {
	tx, err := store.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	q := New(tx)
	err = fn(q)
	if err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("tx err: %v , rb err := %v", err, rbErr)
		}
		return err
	}

	return tx.Commit()
}
